/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudbasico;

import java.sql.Connection;
import com.mysql.cj.protocol.Resultset;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Omaroa omaroaing@gmail.com
 */
public class FormularioClientes extends javax.swing.JFrame {
    Connection con;
    Statement sentencia;
    /**
     * Creates new form FormularioClientes
     */
    public FormularioClientes() {
        initComponents();
        ListadoClientes();
    }
    
    public void ListadoClientes(){
        
        String[] columnas= {"Id", "Nombre", "Apellido", "Cedula", "Direccion","Telefono"};
        String[] registros= new String[6];
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        
        try {
            ConexionDB conexiondb = new ConexionDB();
            con = conexiondb.getConnection();
            sentencia = con.createStatement();
            String sql = "SELECT * FROM clientes;";
            ResultSet resultado= sentencia.executeQuery(sql);
            
            while (resultado.next()){
                registros[0]= resultado.getString("Id");
                registros[1]= resultado.getString("Nombre");
                registros[2]= resultado.getString("Apellido");
                registros[3]= resultado.getString("Cc");
                registros[4]= resultado.getString("Direccion");
                registros[5]= resultado.getString("Telefono");
                modelo.addRow(registros);    
            }
            
            TablaClientes.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(FormularioClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nombre = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        Apellido = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        Cc = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        Direccion = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        Telefono = new java.awt.TextField();
        Guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Id = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        Nombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        Apellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cc");

        Cc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Direccion");

        Direccion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Telefono");

        Telefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Guardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Guardar.setText("Guardar en BD");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Formulario Registro de Clientes");

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Cedula", "Direccion", "Telefono"
            }
        ));
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaClientes);

        Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Actualizar.setText("Actualizar en DB");
        Actualizar.setActionCommand("Actualizar en DB");
        Actualizar.setEnabled(false);
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Eliminar.setText("Eliminar en DB");
        Eliminar.setEnabled(false);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Id.setEditable(false);
        Id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(313, 313, 313))))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String nombre= Nombre.getText();
        String apellido= Apellido.getText();
        String cc= Cc.getText();
        String direccion= Direccion.getText();
        String telefono= Telefono.getText();
        
        if(direccion.equals("") || telefono.equals("") || nombre.equals("") || apellido.equals("") || cc.equals("")){
        JOptionPane.showMessageDialog(null, "Todos los datos son obligatorios. Por favor completelos");
        }
        else{
                      
            ConexionDB conexiondb = new ConexionDB();
            con = conexiondb.getConnection();
            try {
                sentencia = con.createStatement();
                sentencia.executeUpdate("INSERT INTO clientes(Id,Nombre,Apellido,Cc,Direccion,Telefono) VALUES(NULL,'"+nombre+"','"+apellido+"','"+cc+"','"+direccion+"','"+telefono+"')" );
                JOptionPane.showMessageDialog(null, "Registro guardado con exito!!!");
                Nombre.setText("");
                Apellido.setText("");
                Cc.setText("");
                Direccion.setText("");
                Telefono.setText("");
                Id.setText("");
                ListadoClientes();

            } catch (SQLException ex) {
                Logger.getLogger(FormularioClientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Fallo el registro, por favor intente de nuevo");
            }
        }

    }//GEN-LAST:event_GuardarActionPerformed

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        
        int fila =TablaClientes.getSelectedRow();
        String id = TablaClientes.getValueAt(fila, 0).toString();
        String nombre = (String) TablaClientes.getValueAt(fila, 1);
        String apellido = (String) TablaClientes.getValueAt(fila, 2);
        String cc = (String) TablaClientes.getValueAt(fila, 3);
        String direccion = (String) TablaClientes.getValueAt(fila, 4);
        String telefono = (String) TablaClientes.getValueAt(fila, 5);
        Id.setText(id);
        Nombre.setText(nombre);
        Apellido.setText(apellido);
        Cc.setText(cc);
        Direccion.setText(direccion);
        Telefono.setText(telefono);
        Actualizar.setEnabled(true);
        Eliminar.setEnabled(true);
        Guardar.setEnabled(false);
        
    }//GEN-LAST:event_TablaClientesMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        String id= Id.getText();
        String nombre= Nombre.getText();
        String apellido= Apellido.getText();
        String cc= Cc.getText();
        String direccion= Direccion.getText();
        String telefono= Telefono.getText();
        
        if(direccion.equals("") || telefono.equals("") || nombre.equals("") || apellido.equals("") || cc.equals("")){
        JOptionPane.showMessageDialog(null, "Todos los datos son obligatorios. Por favor completelos");
        }
        else{
            ConexionDB conexiondb = new ConexionDB();
            con = conexiondb.getConnection();
            try {
                sentencia = con.createStatement();
                sentencia.executeUpdate("UPDATE clientes SET Nombre='"+nombre+"',Apellido='"+apellido+"',Cc='"+cc+"',Direccion='"+direccion+"',Telefono='"+telefono+"' WHERE Id='"+id+"'" );
                JOptionPane.showMessageDialog(null, "Usuario actualizado con exito!!!");
                Id.setText("");
                Nombre.setText("");
                Apellido.setText("");
                Cc.setText("");
                Direccion.setText("");
                Telefono.setText("");
                Id.setText("");
                ListadoClientes();
                Guardar.setEnabled(true);
                Actualizar.setEnabled(false);
                Eliminar.setEnabled(false);

            } catch (SQLException ex) {
                Logger.getLogger(FormularioClientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Fallo la actualizacion, por favor intente de nuevo");
            }
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
        String id= Id.getText();
        ConexionDB conexiondb = new ConexionDB();
        con = conexiondb.getConnection();
            try {
                sentencia = con.createStatement();
                sentencia.executeUpdate("DELETE FROM clientes WHERE Id='"+id+"'" );
                JOptionPane.showMessageDialog(null, "Usuario Eliminado con exito!!!");
                Id.setText("");
                Nombre.setText("");
                Apellido.setText("");
                Cc.setText("");
                Direccion.setText("");
                Telefono.setText("");
                ListadoClientes();
                Guardar.setEnabled(true);
                Actualizar.setEnabled(false);
                Eliminar.setEnabled(false);

            } catch (SQLException ex) {
                Logger.getLogger(FormularioClientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Fallo la eliminacion, por favor intente de nuevo");
            }        
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioClientes().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private java.awt.TextField Apellido;
    private java.awt.TextField Cc;
    private java.awt.TextField Direccion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private java.awt.TextField Id;
    private java.awt.TextField Nombre;
    private javax.swing.JTable TablaClientes;
    private java.awt.TextField Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
